// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <stdio.h>

// Include the trusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_t.h"

void handle_message_sanitize(char *string_ptr)
{

    fprintf(stdout, "Char is %lu byte, string_ptr at %lx\n", sizeof(char), (unsigned long) string_ptr);
    fprintf(stdout, "String sent to the enclave has %lu chars\n", strlen(string_ptr));
    fprintf(stdout, "String sent to the enclave: %s\n", string_ptr);
  
    fprintf(stdout, "Enclave heap (starting from string_ptr) before operation:\n");
    for(unsigned int i = 0; i < 128; i++)
    {
     	fprintf(stdout, "%02x ", (uint8_t)string_ptr[i]);
    }
    fprintf(stdout, "\n");

    // Let's assume this is the actual enclave code
    
    // Remove all special characters and replace with space (0x20)
    for(size_t i = 0; i < strlen(string_ptr); i++)
    {
        if(!isalnum(string_ptr[i]))
        {
            string_ptr[i] = 0x20;
        }
    }

    // Assume further stuff going on here
   
    fprintf(stdout, "Enclave heap (starting from string_ptr) after operation:\n");
    for(unsigned int i = 0; i < 128; i++)
    {
     	fprintf(stdout, "%02x ", (uint8_t)string_ptr[i]);
    }
    fprintf(stdout, "\n");
}

